version: "3.9"

services:
  server:
    build: ./nginx
    container_name: jwt_auth_nginx
    ports:
      - 80:80
      - 443:443
    restart: "on-failure"
    depends_on:
      - web

  web:
    build: .
    container_name: jwt_auth
    command: sh -c "go build main.go && ./main"
    
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    restart: "on-failure"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: jwt_auth_db
    environment:
      - POSTGRES_DB=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: "on-failure"
volumes:
  pgdata:
